import type { Locale } from "@/lib/i18n"

export const localizedUiText = {
  en: {
    unauthorized: "Unauthorized",
    forbidden: "Forbidden",
    createBusiness: "Create business",
    businessesTitle: "Businesses",
    aiAssistantTitle: "AI Assistant",
    knowledgeTitle: "Knowledge",
    knowledgeBaseTitle: "Knowledge Base",
    productsTitle: "Products",
    servicesTitle: "Services",
    policiesFaqsTitle: "Policies and FAQs",
    channelsTitle: "Channels",
    humanHandoffTitle: "Human Handoff",
    actionsTitle: "Actions and Approvals",
    followupsTitle: "Follow-ups",
    testLabTitle: "Test Lab",
    analyticsTitle: "Analytics",
    teamTitle: "Team",
    apiKeysTitle: "Internal API Keys",
    auditLogsTitle: "Audit Logs",
    systemHealthTitle: "System Health",
    accountTitle: "Account Settings",
    manageTenantSettings: "Manage tenant settings stored in ReplyOps.",
    name: "Name",
    slug: "Slug",
    industry: "Industry",
    timezone: "Timezone",
    supportedLanguages: "Supported languages",
    currency: "Currency",
    description: "Description",
    enabled: "Enabled",
    disabled: "Disabled",
    create: "Create",
    save: "Save",
    signOut: "Sign Out",
    changePasswordSentence: "Change password",
    restore: "Restore",
    archive: "Archive",
    primaryLanguage: "Primary language",
    retentionDays: "Retention days",
    noBusinessesFound: "No businesses found",
    createBusinessToStart: "Create a business to start tenant-scoped configuration.",
    aiAssistantSettings: "AI Assistant Settings",
    assistantSettingsDescription: "Database-backed runtime configuration for Test Lab and live channels.",
    profile: "Profile",
    assistantName: "Assistant name",
    dialect: "Dialect",
    tone: "Tone",
    replyLength: "Reply length",
    emojiPolicy: "Emoji policy",
    customerMessages: "Customer Messages",
    greeting: "Greeting",
    helpMessage: "Help message",
    apologyStyle: "Apology style",
    escalationStyle: "Escalation style",
    guardrails: "Guardrails",
    confidenceThreshold: "Confidence threshold",
    groundingThreshold: "Grounding threshold",
    memoryLength: "Memory length",
    maxReplyChars: "Max reply chars",
    enabledActions: "Enabled actions",
    approvalRequiredActions: "Approval-required actions",
    businessHoursBehavior: "Business-hours behavior",
    offlineResponseBehavior: "Offline response behavior",
    systemRules: "System rules",
    prohibitedTopics: "Prohibited topics",
    selectBusinessFirst: "Please create or select a business first.",
    knowledgeBase: "Knowledge Base",
    knowledgeDescription: "Create, edit, archive, restore, and re-index tenant-scoped knowledge.",
    addManualText: "Add manual text",
    title: "Title",
    content: "Content",
    createAndIndex: "Create and index",
    chunks: "chunks",
    saveAndReindex: "Save and re-index",
    reindex: "Re-index",
    knowledgeContent: "Knowledge content",
    noDocumentsFound: "No documents found",
    addManualTextFirst: "Add manual text to create the first searchable source.",
    productsDescription: "Real product records available to AI answers and actions.",
    productsUnavailable: "Create/edit controls are disabled until product mutation forms are connected to audited server actions.",
    noProductsStored: "No products stored.",
    variants: "variants",
    servicesDescription: "Service catalog records used for grounded support answers.",
    servicesUnavailable: "Create/edit controls are disabled until service mutation forms are connected to audited server actions.",
    noServicesStored: "No services stored.",
    noDuration: "No duration",
    policiesDescription: "Tenant policies and frequent answers used as governed knowledge.",
    policiesUnavailable: "Create/edit controls are disabled until policy and FAQ mutation forms are connected to audited server actions.",
    policies: "Policies",
    faqs: "FAQs",
    noPoliciesStored: "No policies stored.",
    noFaqsStored: "No FAQs stored.",
    channelsDescription: "Connect Telegram, Web Chat, and WhatsApp credentials. Secrets are encrypted and never shown after save.",
    telegramDescription: "Validates `getMe`, stores the token encrypted, creates a connection ID, and registers the ReplyOps webhook.",
    business: "Business",
    botToken: "Bot token",
    authorizationHeaderValue: "Authorization header value",
    connectTelegram: "Connect Telegram",
    webChatDescription: "Creates a public key, origin allowlist, embed endpoint, and runtime chat connection.",
    assistantDefault: "Assistant",
    webChatWelcomeDefault: "How can I help?",
    widgetTitle: "Widget title",
    welcomeMessage: "Welcome message",
    brandColor: "Brand color",
    allowedOrigins: "Allowed origins",
    createWebChat: "Create Web Chat",
    whatsAppDescription: "Software path is implemented; live connection requires approved Meta credentials.",
    appId: "App ID",
    appSecret: "App Secret",
    accessToken: "Access Token",
    phoneNumberId: "Phone Number ID",
    businessAccountId: "Business Account ID",
    verifyToken: "Verify Token",
    validateAndConnect: "Validate and Connect",
    noChannelConnections: "No channel connections",
    connectChannelPrompt: "Connect Telegram, create a Web Chat widget, or add Meta credentials for WhatsApp.",
    disconnect: "Disconnect",
    conversationsDescription: "Three-panel support inbox with persisted message history, delivery state, sources, handoff state, and customer context.",
    noConversationsYet: "No conversations yet",
    conversationsEmptyDescription: "Telegram, Web Chat, WhatsApp, or Test Lab messages will appear here after they are persisted.",
    inbox: "Inbox",
    conversations: "Conversations",
    recentConversationsSuffix: "recent conversations",
    conversation: "Conversation",
    noExternalThread: "No external thread",
    knowledgeGap: "Knowledge gap",
    confidence: "confidence",
    customer: "Customer",
    externalId: "External ID",
    phone: "Phone",
    notStored: "Not stored",
    aiAndHandoff: "AI and handoff",
    automation: "Automation",
    latestHandoff: "Latest handoff",
    none: "none",
    internalNotes: "Internal notes",
    noNotes: "No notes.",
    system: "System",
    noMessagesStoredPeriod: "No messages stored.",
    handoffDescription: "Claim customer escalations, add internal notes, reply through connected channels, and resume automation.",
    noHandoffs: "No handoffs",
    handoffsEmptyDescription: "Customer requests for human support will appear here.",
    nobody: "Nobody",
    assigned: "Assigned:",
    claim: "Claim",
    release: "Release",
    resolve: "Resolve",
    resumeAi: "Resume AI",
    recentMessages: "Recent messages",
    agentWorkspace: "Agent workspace",
    writeCustomerReply: "Write customer reply",
    sendReply: "Send reply",
    internalNote: "Internal note",
    addNote: "Add note",
    actionsDescription: "Configure SSRF-guarded HTTP actions, collect execution requests, approve sensitive actions, and retry failures.",
    createHttpAction: "Create HTTP action",
    httpMethod: "HTTP method",
    requiresApproval: "Requires approval",
    headersJson: "Headers JSON",
    requestTemplateJson: "Request template JSON",
    createAction: "Create action",
    noActionDefinitions: "No action definitions stored.",
    approvalRequired: "approval required",
    autoApproved: "auto approved",
    allowedDomainsPrefix: "Allowed domains:",
    publicHostFallback: "resolved host must be public",
    actionInputJson: "Action input JSON",
    createRequest: "Create request",
    noRequestsYet: "No requests yet.",
    request: "Request",
    approve: "Approve",
    reject: "Reject",
    execute: "Execute",
    followupsDescription: "Database-owned follow-up rules and jobs with consent, opt-out, quiet hours, caps, and stop conditions.",
    createRule: "Create rule",
    followupTemplate: "Follow-up template",
    followupTemplateDefault: "Can we help with anything else?",
    consentRequired: "Consent required",
    createRuleButton: "Create rule",
    noFollowupRules: "No follow-up rules stored. Follow-ups are disabled by default.",
    consentOptional: "consent optional",
    scheduleJob: "Schedule job",
    noJobsQueued: "No jobs queued.",
    cancel: "Cancel",
    customerConsent: "Customer consent",
    noCustomersStored: "No customers stored.",
    consented: "consented",
    optedOut: "opted out",
    optOut: "Opt out",
    markConsent: "Mark consent",
    testLabDescription: "Simulate conversations and analyze AI decision making.",
    simulationSession: "Simulation Session",
    reset: "Reset",
    startTyping: "Start typing below to test your assistant's responses.",
    thinking: "Thinking...",
    typeMessage: "Type a message...",
    send: "Send",
    decisionTrace: "Decision Trace",
    intentDetected: "Intent Detected",
    knowledgeQuestion: "Knowledge Question",
    maxConfidence: "Max Confidence",
    knowledgeRetrieved: "Knowledge Retrieved",
    noChunksRetrieved: "No chunks retrieved",
    score: "Score:",
    groundingSafety: "Grounding & Safety",
    groundednessScore: "Groundedness Score",
    yes: "YES",
    no: "NO",
    yesPercent: "100% (YES)",
    noPercent: "0% (NO)",
    noPlain: "No",
    actionSuggested: "Action Suggested",
    reply: "Reply",
    handoffTriggered: "Handoff Triggered",
    analyticsDescription: "Persisted usage and operations metrics. Empty state means no measured events, not zero performance.",
    noUsageMetrics: "No usage metrics recorded.",
    teamDescription: "Invite users, assign tenant roles, remove memberships, and deactivate accounts with audit events.",
    noMembers: "No members",
    noMembersDescription: "Tenant memberships will appear here after users are added.",
    saveRole: "Save role",
    removeMembership: "Remove membership",
    deactivateUser: "Deactivate user",
    reactivateUser: "Reactivate user",
    recentInvitations: "Recent invitations",
    noInvitationsStored: "No invitations stored.",
    inviteMember: "Invite member",
    inviteDescription: "Creates or reactivates a user, assigns tenant role, and records an invitation audit event.",
    invite: "Invite",
    inviting: "Inviting",
    temporaryPasswordShownOnce: "Temporary password shown once:",
    apiKeysDescription: "HMAC credentials for n8n and private runtime integrations.",
    noInternalApiKeys: "No internal API keys stored.",
    auditHistory: "Audit history",
    noApiKeyAuditEvents: "No API key audit events.",
    createInternalApiKey: "Create internal API key",
    tenant: "Tenant",
    expiresAt: "Expires at",
    createKey: "Create key",
    creating: "Creating...",
    keyId: "Key ID:",
    shownOnce: "Shown once",
    rotateKey: "Rotate key",
    apiKeyToRotate: "API key to rotate",
    rotating: "Rotating...",
    rotateAndRevokeOldKey: "Rotate and revoke old key",
    activate: "Activate",
    revoke: "Revoke",
    never: "never",
    noScopes: "No scopes",
    auditLogsDescription: "Security and operational events stored without secret values.",
    noAuditEventsRecorded: "No audit events recorded.",
    platform: "Platform",
    systemHealthDescription: "Live and database-backed health signals from ReplyOps runtime.",
    tenants: "Tenants",
    channelConnections: "Channel connections",
    systemEvents: "System events",
    deadLetters: "Dead letters",
    recentRuntimeEvents: "Recent runtime events",
    noSystemEventsStored: "No system events stored.",
    accountDescription: "Signed-in user identity and security controls.",
    passwordChangeRequired: "Password change required",
    notSet: "Not set",
    platformCredentialReset: "Platform credential reset",
    credentialResetDescription: "Generate a temporary password and force password change at next login.",
    userEmail: "User email",
    generating: "Generating...",
    generateTemporaryPassword: "Generate temporary password",
    loading: "Loading",
    selectBusinessFirstShort: "Please select a business first.",
    onboardingTitle: "Onboarding",
    onboardingDescription: "Tenant-scoped launch progress with validation, persistence, resume, skip, and replay state.",
    businessProfileStep: "Business profile",
    assistantNameStep: "Assistant name",
    languageStep: "Language",
    toneStep: "Tone",
    businessHoursStep: "Business hours",
    knowledgeDocumentStep: "First Knowledge document",
    testLabReadyStep: "Grounded Test Lab question",
    safeChannelStep: "Web Chat or safe QA channel",
    humanHandoffStep: "Human Handoff",
    launchChecklistStep: "Launch checklist",
    noIndustry: "No industry",
    completedStatus: "completed",
    inProgressStatus: "in progress",
    saved: "Saved",
    current: "Current",
    pendingPlain: "Pending",
    previous: "Previous",
    skip: "Skip",
    next: "Next",
    experiencedUserSkip: "Experienced user skip",
  },
  ar: {
    unauthorized: "غير مصرح",
    forbidden: "ممنوع",
    createBusiness: "إنشاء عمل",
    businessesTitle: "الأعمال",
    aiAssistantTitle: "المساعد الذكي",
    knowledgeTitle: "المعرفة",
    knowledgeBaseTitle: "قاعدة المعرفة",
    productsTitle: "المنتجات",
    servicesTitle: "الخدمات",
    policiesFaqsTitle: "السياسات والأسئلة",
    channelsTitle: "القنوات",
    humanHandoffTitle: "التسليم البشري",
    actionsTitle: "الإجراءات والموافقات",
    followupsTitle: "المتابعات",
    testLabTitle: "مختبر الاختبار",
    analyticsTitle: "التحليلات",
    teamTitle: "الفريق",
    apiKeysTitle: "مفاتيح API الداخلية",
    auditLogsTitle: "سجل التدقيق",
    systemHealthTitle: "صحة النظام",
    accountTitle: "إعدادات الحساب",
    manageTenantSettings: "إدارة إعدادات مساحات العمل المخزنة في ReplyOps.",
    name: "الاسم",
    slug: "المعرف",
    industry: "المجال",
    timezone: "المنطقة الزمنية",
    supportedLanguages: "اللغات المدعومة",
    currency: "العملة",
    description: "الوصف",
    enabled: "مفعل",
    disabled: "معطل",
    create: "إنشاء",
    save: "حفظ",
    signOut: "تسجيل الخروج",
    changePasswordSentence: "تغيير كلمة المرور",
    restore: "استعادة",
    archive: "أرشفة",
    primaryLanguage: "اللغة الأساسية",
    retentionDays: "أيام الاحتفاظ",
    noBusinessesFound: "لا توجد أعمال",
    createBusinessToStart: "أنشئ عملاً لبدء إعدادات معزولة حسب مساحة العمل.",
    aiAssistantSettings: "إعدادات المساعد الذكي",
    assistantSettingsDescription: "إعدادات تشغيل مخزنة في قاعدة البيانات لمختبر الاختبار والقنوات الحية.",
    profile: "الملف",
    assistantName: "اسم المساعد",
    dialect: "اللهجة",
    tone: "النبرة",
    replyLength: "طول الرد",
    emojiPolicy: "سياسة الرموز",
    customerMessages: "رسائل العملاء",
    greeting: "التحية",
    helpMessage: "رسالة المساعدة",
    apologyStyle: "أسلوب الاعتذار",
    escalationStyle: "أسلوب التصعيد",
    guardrails: "ضوابط الأمان",
    confidenceThreshold: "حد الثقة",
    groundingThreshold: "حد الاستناد",
    memoryLength: "طول الذاكرة",
    maxReplyChars: "أقصى أحرف للرد",
    enabledActions: "الإجراءات المفعلة",
    approvalRequiredActions: "إجراءات تتطلب موافقة",
    businessHoursBehavior: "سلوك ساعات العمل",
    offlineResponseBehavior: "سلوك الرد خارج الاتصال",
    systemRules: "قواعد النظام",
    prohibitedTopics: "الموضوعات المحظورة",
    selectBusinessFirst: "يرجى إنشاء أو اختيار عمل أولاً.",
    knowledgeBase: "قاعدة المعرفة",
    knowledgeDescription: "إنشاء وتعديل وأرشفة واستعادة وإعادة فهرسة معرفة مساحة العمل.",
    addManualText: "إضافة نص يدوي",
    title: "العنوان",
    content: "المحتوى",
    createAndIndex: "إنشاء وفهرسة",
    chunks: "أجزاء",
    saveAndReindex: "حفظ وإعادة فهرسة",
    reindex: "إعادة فهرسة",
    knowledgeContent: "محتوى المعرفة",
    noDocumentsFound: "لا توجد مستندات",
    addManualTextFirst: "أضف نصاً يدوياً لإنشاء أول مصدر قابل للبحث.",
    productsDescription: "سجلات منتجات حقيقية متاحة لإجابات المساعد والإجراءات.",
    productsUnavailable: "تعطلت أدوات الإنشاء والتعديل حتى يتم ربط نماذج المنتجات بإجراءات خادم مدققة.",
    noProductsStored: "لا توجد منتجات مخزنة.",
    variants: "متغيرات",
    servicesDescription: "سجلات كتالوج الخدمات المستخدمة في الإجابات المستندة إلى مصادر.",
    servicesUnavailable: "تعطلت أدوات الإنشاء والتعديل حتى يتم ربط نماذج الخدمات بإجراءات خادم مدققة.",
    noServicesStored: "لا توجد خدمات مخزنة.",
    noDuration: "لا توجد مدة",
    policiesDescription: "سياسات وإجابات متكررة للمساحة تستخدم كمعرفة محكومة.",
    policiesUnavailable: "تعطلت أدوات الإنشاء والتعديل حتى يتم ربط نماذج السياسات والأسئلة بإجراءات خادم مدققة.",
    policies: "السياسات",
    faqs: "الأسئلة الشائعة",
    noPoliciesStored: "لا توجد سياسات مخزنة.",
    noFaqsStored: "لا توجد أسئلة شائعة مخزنة.",
    channelsDescription: "ربط بيانات Telegram وWeb Chat وWhatsApp. الأسرار مشفرة ولا تظهر بعد الحفظ.",
    telegramDescription: "يتحقق من `getMe`، ويحفظ الرمز مشفراً، وينشئ معرف اتصال، ويسجل webhook ReplyOps.",
    business: "العمل",
    botToken: "رمز البوت",
    authorizationHeaderValue: "قيمة ترويسة Authorization",
    connectTelegram: "ربط Telegram",
    webChatDescription: "ينشئ مفتاحاً عاماً وقائمة أصول مسموحة ونقطة تضمين واتصال محادثة.",
    assistantDefault: "المساعد",
    webChatWelcomeDefault: "كيف يمكنني المساعدة؟",
    widgetTitle: "عنوان الودجت",
    welcomeMessage: "رسالة الترحيب",
    brandColor: "لون العلامة",
    allowedOrigins: "الأصول المسموحة",
    createWebChat: "إنشاء Web Chat",
    whatsAppDescription: "مسار البرنامج منفذ؛ الاتصال الحي يحتاج بيانات Meta معتمدة.",
    appId: "معرف التطبيق",
    appSecret: "سر التطبيق",
    accessToken: "رمز الوصول",
    phoneNumberId: "معرف رقم الهاتف",
    businessAccountId: "معرف حساب العمل",
    verifyToken: "رمز التحقق",
    validateAndConnect: "تحقق واربط",
    noChannelConnections: "لا توجد اتصالات قنوات",
    connectChannelPrompt: "اربط Telegram أو أنشئ Web Chat أو أضف بيانات Meta لـ WhatsApp.",
    disconnect: "قطع الاتصال",
    conversationsDescription: "صندوق دعم بثلاث لوحات مع تاريخ رسائل وحالة تسليم ومصادر وتسليم بشري وسياق عميل.",
    noConversationsYet: "لا توجد محادثات بعد",
    conversationsEmptyDescription: "ستظهر رسائل Telegram أو Web Chat أو WhatsApp أو مختبر الاختبار هنا بعد حفظها.",
    inbox: "صندوق الوارد",
    conversations: "المحادثات",
    recentConversationsSuffix: "محادثات حديثة",
    conversation: "محادثة",
    noExternalThread: "لا يوجد مسار خارجي",
    knowledgeGap: "فجوة معرفة",
    confidence: "ثقة",
    customer: "العميل",
    externalId: "المعرف الخارجي",
    phone: "الهاتف",
    notStored: "غير مخزن",
    aiAndHandoff: "الذكاء والتسليم",
    automation: "الأتمتة",
    latestHandoff: "آخر تسليم",
    none: "لا يوجد",
    internalNotes: "ملاحظات داخلية",
    noNotes: "لا توجد ملاحظات.",
    system: "النظام",
    noMessagesStoredPeriod: "لا توجد رسائل مخزنة.",
    handoffDescription: "استلام تصعيدات العملاء وإضافة ملاحظات داخلية والرد عبر القنوات واستئناف الأتمتة.",
    noHandoffs: "لا توجد طلبات تسليم",
    handoffsEmptyDescription: "ستظهر هنا طلبات العملاء للدعم البشري.",
    nobody: "لا أحد",
    assigned: "المكلف:",
    claim: "استلام",
    release: "ترك",
    resolve: "حل",
    resumeAi: "استئناف المساعد",
    recentMessages: "آخر الرسائل",
    agentWorkspace: "مساحة عمل الوكيل",
    writeCustomerReply: "اكتب رد العميل",
    sendReply: "إرسال الرد",
    internalNote: "ملاحظة داخلية",
    addNote: "إضافة ملاحظة",
    actionsDescription: "إعداد إجراءات HTTP محمية من SSRF وجمع طلبات التنفيذ واعتماد الإجراءات الحساسة وإعادة المحاولة.",
    createHttpAction: "إنشاء إجراء HTTP",
    httpMethod: "طريقة HTTP",
    requiresApproval: "يتطلب موافقة",
    headersJson: "ترويسات JSON",
    requestTemplateJson: "قالب طلب JSON",
    createAction: "إنشاء إجراء",
    noActionDefinitions: "لا توجد تعريفات إجراءات مخزنة.",
    approvalRequired: "يتطلب موافقة",
    autoApproved: "معتمد تلقائياً",
    allowedDomainsPrefix: "النطاقات المسموحة:",
    publicHostFallback: "يجب أن يكون المضيف عاماً",
    actionInputJson: "مدخل الإجراء JSON",
    createRequest: "إنشاء طلب",
    noRequestsYet: "لا توجد طلبات بعد.",
    request: "طلب",
    approve: "موافقة",
    reject: "رفض",
    execute: "تنفيذ",
    followupsDescription: "قواعد ومهام متابعة مملوكة لقاعدة البيانات مع موافقة وإلغاء وهدوء وحدود وشروط إيقاف.",
    createRule: "إنشاء قاعدة",
    followupTemplate: "قالب المتابعة",
    followupTemplateDefault: "هل يمكننا مساعدتك في شيء آخر؟",
    consentRequired: "الموافقة مطلوبة",
    createRuleButton: "إنشاء قاعدة",
    noFollowupRules: "لا توجد قواعد متابعة مخزنة. المتابعات معطلة افتراضياً.",
    consentOptional: "الموافقة اختيارية",
    scheduleJob: "جدولة مهمة",
    noJobsQueued: "لا توجد مهام في القائمة.",
    cancel: "إلغاء",
    customerConsent: "موافقة العميل",
    noCustomersStored: "لا يوجد عملاء مخزنون.",
    consented: "وافق",
    optedOut: "ألغى الاشتراك",
    optOut: "إلغاء الاشتراك",
    markConsent: "تسجيل الموافقة",
    testLabDescription: "محاكاة المحادثات وتحليل قرارات الذكاء الاصطناعي.",
    simulationSession: "جلسة المحاكاة",
    reset: "إعادة ضبط",
    startTyping: "ابدأ الكتابة أدناه لاختبار ردود المساعد.",
    thinking: "يفكر...",
    typeMessage: "اكتب رسالة...",
    send: "إرسال",
    decisionTrace: "مسار القرار",
    intentDetected: "النية المكتشفة",
    knowledgeQuestion: "سؤال معرفة",
    maxConfidence: "أعلى ثقة",
    knowledgeRetrieved: "المعرفة المسترجعة",
    noChunksRetrieved: "لا توجد أجزاء مسترجعة",
    score: "الدرجة:",
    groundingSafety: "الاستناد والأمان",
    groundednessScore: "درجة الاستناد",
    yes: "نعم",
    no: "لا",
    yesPercent: "١٠٠٪ (نعم)",
    noPercent: "٠٪ (لا)",
    noPlain: "لا",
    actionSuggested: "الإجراء المقترح",
    reply: "رد",
    handoffTriggered: "تفعيل التسليم",
    analyticsDescription: "مقاييس استخدام وعمليات محفوظة. الحالة الفارغة تعني غياب أحداث مقاسة لا أداء صفري.",
    noUsageMetrics: "لا توجد مقاييس استخدام مسجلة.",
    teamDescription: "دعوة المستخدمين وتعيين الأدوار وإزالة العضويات وتعطيل الحسابات مع أحداث تدقيق.",
    noMembers: "لا يوجد أعضاء",
    noMembersDescription: "ستظهر عضويات مساحة العمل هنا بعد إضافة المستخدمين.",
    saveRole: "حفظ الدور",
    removeMembership: "إزالة العضوية",
    deactivateUser: "تعطيل المستخدم",
    reactivateUser: "إعادة تفعيل المستخدم",
    recentInvitations: "آخر الدعوات",
    noInvitationsStored: "لا توجد دعوات مخزنة.",
    inviteMember: "دعوة عضو",
    inviteDescription: "ينشئ أو يعيد تفعيل مستخدم ويعين دوراً ويسجل حدث دعوة.",
    invite: "دعوة",
    inviting: "جارٍ الدعوة",
    temporaryPasswordShownOnce: "كلمة مرور مؤقتة تظهر مرة واحدة:",
    apiKeysDescription: "بيانات HMAC لـ n8n والتكاملات الداخلية الخاصة.",
    noInternalApiKeys: "لا توجد مفاتيح API داخلية مخزنة.",
    auditHistory: "سجل التدقيق",
    noApiKeyAuditEvents: "لا توجد أحداث تدقيق لمفاتيح API.",
    createInternalApiKey: "إنشاء مفتاح API داخلي",
    tenant: "مساحة العمل",
    expiresAt: "ينتهي في",
    createKey: "إنشاء مفتاح",
    creating: "جارٍ الإنشاء...",
    keyId: "معرف المفتاح:",
    shownOnce: "يظهر مرة واحدة",
    rotateKey: "تدوير المفتاح",
    apiKeyToRotate: "مفتاح API للتدوير",
    rotating: "جارٍ التدوير...",
    rotateAndRevokeOldKey: "تدوير وإلغاء المفتاح القديم",
    activate: "تفعيل",
    revoke: "إلغاء",
    never: "أبداً",
    noScopes: "لا توجد صلاحيات",
    auditLogsDescription: "أحداث أمان وعمليات محفوظة دون قيم الأسرار.",
    noAuditEventsRecorded: "لا توجد أحداث تدقيق مسجلة.",
    platform: "المنصة",
    systemHealthDescription: "إشارات صحة حية ومخزنة من تشغيل ReplyOps.",
    tenants: "مساحات العمل",
    channelConnections: "اتصالات القنوات",
    systemEvents: "أحداث النظام",
    deadLetters: "Dead Letters",
    recentRuntimeEvents: "آخر أحداث التشغيل",
    noSystemEventsStored: "لا توجد أحداث نظام مخزنة.",
    accountDescription: "هوية المستخدم المسجل وضوابط الأمان.",
    passwordChangeRequired: "تغيير كلمة المرور مطلوب",
    notSet: "غير محدد",
    platformCredentialReset: "إعادة ضبط اعتماد المنصة",
    credentialResetDescription: "إنشاء كلمة مرور مؤقتة وفرض تغييرها عند تسجيل الدخول التالي.",
    userEmail: "بريد المستخدم",
    generating: "جارٍ الإنشاء...",
    generateTemporaryPassword: "إنشاء كلمة مرور مؤقتة",
    loading: "جارٍ التحميل",
    selectBusinessFirstShort: "يرجى اختيار عمل أولاً.",
    onboardingTitle: "الإعداد الأولي",
    onboardingDescription: "تقدم إطلاق مساحة العمل مع التحقق والحفظ والاستئناف والتخطي وإعادة الجولة.",
    businessProfileStep: "ملف العمل",
    assistantNameStep: "اسم المساعد",
    languageStep: "اللغة",
    toneStep: "النبرة",
    businessHoursStep: "ساعات العمل",
    knowledgeDocumentStep: "أول مستند معرفة",
    testLabReadyStep: "سؤال مختبر اختبار مستند",
    safeChannelStep: "Web Chat أو قناة اختبار آمنة",
    humanHandoffStep: "التسليم البشري",
    launchChecklistStep: "قائمة الإطلاق",
    noIndustry: "لا يوجد مجال",
    completedStatus: "مكتمل",
    inProgressStatus: "قيد التنفيذ",
    saved: "محفوظ",
    current: "الحالي",
    pendingPlain: "معلق",
    previous: "السابق",
    skip: "تخطي",
    next: "التالي",
    experiencedUserSkip: "تخطي للمستخدم الخبير",
  },
} as const

export type LocalizedUiTextKey = keyof typeof localizedUiText.en

export const englishTextToKey = new Map<string, LocalizedUiTextKey>(
  Object.entries(localizedUiText.en).map(([key, value]) => [value, key as LocalizedUiTextKey]),
)

export function localizeExactText(value: string, locale: Locale) {
  if (locale === "en") return value
  const key = englishTextToKey.get(value.trim())
  if (key) return value.replace(value.trim(), localizedUiText.ar[key])
  return value
    .replace(/\brecent conversations\b/g, localizedUiText.ar.recentConversationsSuffix)
    .replace(/\bchunks\b/g, localizedUiText.ar.chunks)
    .replace(/\bvariants\b/g, localizedUiText.ar.variants)
    .replace(/\bconfidence\b/g, localizedUiText.ar.confidence)
    .replace(/\bAllowed domains:/g, localizedUiText.ar.allowedDomainsPrefix)
    .replace(/\bRequest\b/g, localizedUiText.ar.request)
    .replace(/\bQuiet hours\b/g, "ساعات الهدوء")
    .replace(/\bmax attempts\b/g, "أقصى محاولات")
    .replace(/\bminimum delay\b/g, "أقل تأخير")
    .replace(/\bScheduled\b/g, "مجدولة")
    .replace(/\battempts\b/g, "محاولات")
    .replace(/\bcreated\b/g, "أنشئ")
    .replace(/\blast used\b/g, "آخر استخدام")
    .replace(/\bexpires\b/g, "ينتهي")
    .replace(/\bactive tenants\b/g, "مساحات عمل نشطة")
    .replace(/\bchannel records\b/g, "سجلات قنوات")
    .replace(/\brecent events loaded\b/g, "أحداث حديثة محملة")
    .replace(/\brecords loaded\b/g, "سجلات محملة")
    .replace(/\bpending jobs\b/g, "مهام معلقة")
    .replace(/\bfailed Knowledge documents\b/g, "مستندات معرفة فاشلة")
    .replace(/\bopen or recent records loaded\b/g, "سجلات مفتوحة أو حديثة محملة")
    .replace(/\breturned HTTP\b/g, "أعاد HTTP")
    .replace(/\bDatabase query succeeded\./g, "نجح استعلام قاعدة البيانات.")
    .replace(/\bDatabase query failed\./g, "فشل استعلام قاعدة البيانات.")
    .replace(/\bCredential presence only; no secret exposed\./g, "وجود الاعتماد فقط؛ لا تُعرض أسرار.")
    .replace(/\bRecent provider failure or quota event recorded\./g, "سُجل فشل مزود أو حدث حصة حديث.")
    .replace(/\bTelegram channel has stored credentials\./g, "قناة Telegram لديها بيانات محفوظة.")
    .replace(/\bNo Telegram credentials stored\./g, "لا توجد بيانات Telegram محفوظة.")
    .replace(/\bWeb Chat public key configuration exists\./g, "إعداد مفتاح Web Chat العام موجود.")
    .replace(/\bNo Web Chat connection configured\./g, "لا يوجد اتصال Web Chat معد.")
    .replace(/\bWhatsApp credentials are stored\./g, "بيانات WhatsApp محفوظة.")
    .replace(/\bMeta credentials are missing\./g, "بيانات Meta غير موجودة.")
}
